export const environment = {
  production: true,
  apiUrl: 'https://api.photocalia.com/v1',
  appVersion: '4.8.0',
  contribution: {
    coffeeUrl: 'https://ko-fi.com/photocalia',
    snackUrl: 'https://ko-fi.com/photocalia',
    mealUrl: 'https://ko-fi.com/photocalia',
  },
  firebase: {
    apiKey: 'AIzaSyDvQ4aCcWtSxGmTXefINTcsdb0O5zheYzE',
    authDomain: 'image-to-ics.firebaseapp.com',
    projectId: 'image-to-ics',
    storageBucket: 'image-to-ics.firebasestorage.app',
    messagingSenderId: '345022501803',
    appId: '1:345022501803:web:3515e39c6c5962806678ee',
    measurementId: 'G-LEY4E6R8Q5',
  },
  footer: {
    enableRepositoryLink: false,
    enableIssuesLink: false,
    enableDocsLink: false,
    enableLicenseLink: true,
    enableSecurityLink: false,
    enableCommunityLink: false,
    enableDiscussionsLink: false,
    enableAboutMeLink: false,
    enablePrivacyLink: true,
    enableTermsLink: true,
    enableLegalMentionsLink: true,
  },
};
