export const environment = {
  production: true,
  apiUrl: 'https://api.photocalia.com/v1',
  appVersion: '4.9.1',
  contribution: {
    coffeeUrl: 'https://buy.stripe.com/4gM4gA09TalwgRAd7m4Vy01',
    snackUrl: 'https://buy.stripe.com/3cI3cw3m565g9p82sI4Vy00',
    mealUrl: 'https://buy.stripe.com/28E28s1dX79keJs1oE4Vy02',
  },
  firebase: {
    apiKey: 'AIzaSyDvQ4aCcWtSxGmTXefINTcsdb0O5zheYzE',
    authDomain: 'image-to-ics.firebaseapp.com',
    projectId: 'image-to-ics',
    storageBucket: 'image-to-ics.firebasestorage.app',
    messagingSenderId: '345022501803',
    appId: '1:345022501803:web:3515e39c6c5962806678ee',
    measurementId: 'G-LEY4E6R8Q5',
  },
  footer: {
    enableRepositoryLink: false,
    enableIssuesLink: false,
    enableDocsLink: false,
    enableLicenseLink: true,
    enableSecurityLink: false,
    enableCommunityLink: false,
    enableDiscussionsLink: false,
    enableAboutMeLink: false,
    enablePrivacyLink: true,
    enableTermsLink: true,
    enableLegalMentionsLink: true,
  },
};
