import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { marked } from 'marked';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = path.join(root, 'content', 'blog');
const outputFile = path.join(root, 'src', 'app', 'pages', 'blog', 'generated', 'blog.generated.ts');
const routesFile = path.join(contentDir, 'prerender-routes.txt');

const requiredSharedFields = [
  'slug',
  'title',
  'description',
  'author',
  'authorUrl',
  'datePublished',
  'dateModified',
  'readingTime',
  'tags',
  'image',
  'imageAlt',
  'keywords',
];
const requiredLocalizedFields = ['title', 'description', 'imageAlt'];

function requireFields(data, fields, source) {
  for (const field of fields) {
    if (data[field] === undefined || data[field] === '') {
      throw new Error(`${source}: missing front matter field "${field}"`);
    }
  }
}

function renderMarkdown(markdown) {
  const html = marked.parse(markdown, {
    async: false,
    gfm: true,
  });

  return html
    .replace('<p>', '<p class="lead">')
    .replaceAll('<a href="http', '<a target="_blank" rel="noopener noreferrer" href="http')
    .trim();
}

function normalizeDate(value, source, field) {
  if (value instanceof Date && !Number.isNaN(value.valueOf())) {
    return value.toISOString().slice(0, 10);
  }
  if (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return value;
  }
  throw new Error(`${source}: "${field}" must use YYYY-MM-DD format`);
}

async function readMarkdown(file, fields) {
  const source = await readFile(file, 'utf8');
  const parsed = matter(source);
  requireFields(parsed.data, fields, path.relative(root, file));

  return {
    data: parsed.data,
    contentHtml: renderMarkdown(parsed.content),
  };
}

const directories = (await readdir(contentDir, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const articles = [];

for (const directory of directories) {
  const articleDir = path.join(contentDir, directory);
  const english = await readMarkdown(path.join(articleDir, 'index.md'), requiredSharedFields);
  const french = await readMarkdown(path.join(articleDir, 'fr.md'), requiredLocalizedFields);

  if (english.data.slug !== directory) {
    throw new Error(
      `${path.relative(root, articleDir)}: directory must match slug "${english.data.slug}"`,
    );
  }
  if (!Array.isArray(english.data.tags) || english.data.tags.length === 0) {
    throw new Error(`${path.relative(root, articleDir)}: "tags" must be a non-empty array`);
  }

  articles.push({
    slug: english.data.slug,
    author: english.data.author,
    authorUrl: english.data.authorUrl,
    datePublished: normalizeDate(
      english.data.datePublished,
      path.relative(root, articleDir),
      'datePublished',
    ),
    dateModified: normalizeDate(
      english.data.dateModified,
      path.relative(root, articleDir),
      'dateModified',
    ),
    readingTime: english.data.readingTime,
    tags: english.data.tags,
    image: english.data.image,
    keywords: english.data.keywords,
    locales: {
      en: {
        title: english.data.title,
        description: english.data.description,
        imageAlt: english.data.imageAlt,
        contentHtml: english.contentHtml,
      },
      fr: {
        title: french.data.title,
        description: french.data.description,
        imageAlt: french.data.imageAlt,
        contentHtml: french.contentHtml,
      },
    },
  });
}

const source = `/* This file is generated by scripts/generate-blog.mjs. Do not edit manually. */
import type { BlogArticle } from '../blog.models';

export const BLOG_ARTICLES = ${JSON.stringify(articles, null, 2)} as const satisfies readonly BlogArticle[];

export const BLOG_SLUGS = BLOG_ARTICLES.map((article) => article.slug);
`;

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(outputFile, source);
await writeFile(
  routesFile,
  `${articles.flatMap((article) => [`/blog/${article.slug}`, `/fr/blog/${article.slug}`]).join('\n')}\n`,
);
console.log(`Generated ${articles.length} blog articles.`);
